name: BuildDocs

on:
  workflow_dispatch:
  release:
    types:
    - published

jobs:
  make_docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - run: python -m pip install sphinx sphinx-rtd-theme sphinx-gallery

    - run: python -m pip install .

    - name: Build docs
      run: |
        cd docs
        make html
        touch build/html/.nojekyll
    - name: Pack docs
      run: tar -cvf docs.tar docs/build/html

    - uses: actions/upload-artifact@v4
      with:
        name: docs
        path: docs.tar

  deploy_docs:
    needs: make_docs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: gh-pages

    - uses: actions/download-artifact@v4
      with:
        name: docs
        path: NewDocs

    - name: Remove old and unpack docs
      run: |
        rm -r docs
        cd NewDocs
        tar -xvf docs.tar
    - name: Move docs
      run:  cp -a --verbose NewDocs/docs/build/html docs

    - name: Commit docs
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add docs
        # This is a slightly messy line to only push if the commit succeeded
        # (because there was changes, but to not throw an error if there was no
        # changes.)
        (git commit -m "Autogenerated new docs" && git push) || true